# Site settings
title: WestsideMS
description: A blog about Minsung Kim @dyros
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Minsung Kim
user_description: Ph.d (2021.08) (Robotics)
user_title:
email: minsungkim@snu.ac.kr
#twitter_username: lorem_ipsum
github_username: "WestsideMS"
gplus_username:  "WestsideMS"

# Google-analytics

# Build settings 
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
